{{- $fullName := include "django.pvc_name" $ -}}
{{ with .Values.django.mediaPersistentVolume }}
{{- if and .enabled (eq .type "pvc") .persistentVolumeClaim.create   }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    exposurex.org/component: django
    app.kubernetes.io/name: {{ include "exposurex.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ include "exposurex.chart" $ }}
    {{- with $.Values.extraLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ $fullName }}
spec:
  accessModes: 
  {{- toYaml .persistentVolumeClaim.accessModes |nindent 4 }}
  resources:
    requests:
      storage: {{ .persistentVolumeClaim.size }}
  {{- if .persistentVolumeClaim.storageClassName }}
  storageClassName: {{ .persistentVolumeClaim.storageClassName }}
  {{- end }}
{{- end }}
{{- end }}
